name: Angular Build

on:
  push:
    branches:
      - main
      - dev
      - base
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug - List Files
        run: ls -R
        working-directory: ${{ github.workspace }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust as needed

      - name: Install dependencies
        run: npm install
        working-directory: ${{ github.workspace }}  # No 'frontend' folder

      - name: Install Angular CLI (Locally)
        run: npm install @angular/cli

      - name: Build Angular App
        run: npx ng build --configuration=production
        working-directory: ${{ github.workspace }}
