name: Angular Build

on:
  push:
    branches:
      - main
      - dev
      - base
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use the Node.js version your project needs

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular App
        run: npx ng build --configuration=production

